name: Deploy Docs

on:
  repository_dispatch:
    types: [docs-publish]

env:
  RELEASES_CREATED: ${{ github.event.client_payload.releases_created }}
  SHA: ${{ github.event.client_payload.sha }}
  TAG: ${{ github.event.client_payload.tag_name }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Client Payload
        run: |
          echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --group docs
      - if: env.RELEASES_CREATED == 'true'
        run: |
          echo "Deploying Release Docs for ${{ env.TAG }}"
          uv run mike deploy --push --update-aliases "${{ env.TAG }}" latest -F mkdocs.yml
          uv run mike set-default --push latest -F mkdocs.yml
      - if: env.RELEASES_CREATED == 'false'
        run: |
          echo "Deploying Edge Docs for ${{ env.SHA }}"
          uv run mike deploy --push --update-aliases edge -F mkdocs.yml
      - run: |
          uv run mike list
