name: Publish CANFAR to PyPI

on:
  repository_dispatch:
    types: [pypi-release]

permissions:
  contents: read

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    concurrency:
      group: pypi-${{ github.event.client_payload.tag_name }}
      cancel-in-progress: true
    permissions:
      id-token: write # Generate OIDC token for attestations
      attestations: write # Attest the build provenance
    environment:
      name: pypi
      url: https://pypi.org/p/canfar
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      -
        name: Echo Build Dispatch
        run: |
          echo "Pypi Release Triggered"
          echo "Event Payload: ${{ toJson(github.event.client_payload) }}"
      -
        name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.client_payload.tag_name }}
      -
        name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: false
      -
        name: Set up Python
        run: uv python install 3.13
      -
        name: Build release distributions
        run: uv build
      -
        name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          attestations: true
          packages-dir: dist/
          verbose: true
          print-hash: true
      -
        name: Attestations for PYPI Wheel
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-path: |
            dist/*.whl
          subject-name: canfar-wheel
          show-summary: true
      -
        name: Attestations for PYPI Source
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-path: |
            dist/*.tar.gz
          subject-name: canfar-source
          show-summary: true
